Organizations:
          - &Org4
            Name: auditorMSP
            ID: auditorMSP
            MSPDir: crypto-config/auditortor/auditortor.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('auditorMSP.admin', 'auditorMSP.peer', 'auditorMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('auditorMSP.admin', 'auditorMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('auditorMSP.admin')"
            AnchorPeers:
                - Host: peer0.auditor.com
                  Port: 1400